
image: continuumio/miniconda3:latest


variables:
  TERM: xterm

before_script:
  ## install os tools
  - apt-get update -q && apt-get install -q -y --no-install-recommends make
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda env create -f environment.yml
  - source activate nannos
  - python -V  # Print out python version for debugging


# stages:
#   - badge
#   # - zenodo
#   - trigdoc
#   - test
  
  

badge:
  script:
    - echo "collecting stats for badges"
    - commits=`git rev-list --all --count`
    - latest_release_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
    - logo=$(cat ./doc/_assets/opt.svg | tr '"' "'")
    - echo {\"schemaVersion\":"1", \"commits\":\"$commits\", \"release_tag\":\"$latest_release_tag\"} > badges.json
    - echo {\"schemaVersion\":"1", \"logoSvg\":\"$logo\", \"label\":\"release\", \"message\":\"$latest_release_tag\", \"color\":\"1672a7\", \"labelColor\":\"dedede\", \"style\":\"for-the-badge\"} > logobadge.json
  artifacts:
    paths:
        - badges.json
        - logobadge.json

staging:
  trigger: nannos/nannos.gitlab.io
  only:
    - master


test:
  script:
    - make install
    - make dev
    - make test
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
  only:
    - master

send-snapshot:
  script:
    - if [[ ! $CI_COMMIT_TAG =~ ^v?[0-9]+\.[0-9]+ ]]; then exit 0; fi
    - pip install gitlab2zenodo
    - git archive --format zip --output ${CI_COMMIT_TAG#v}.zip ${CI_COMMIT_TAG}
    - g2z-send -p -m .zenodo.json ${CI_COMMIT_TAG#v}.zip
  only:
    - tags
