name: nannos
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.8
  - pip
  - numpy
  - scipy
  - matplotlib-base
  - shapely
  - joblib
  - colorlog
  - psutil
  - ipython
  - nlopt
  - pytorch
  - pytorch-gpu
  - jax
  - jaxlib
  - magma
  - pyvista
  - trame
  - ipywidgets
  - ipyvtklink
  - panel
  - autograd
  - pip:
    - git+https://gitlab.com/nannos/nannos.git
