name: nannos
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.8
  - pip
  - numpy
  - scipy
  - matplotlib-base
  - shapely
  - joblib
  - colorlog
  - psutil
  - ipython
  - nlopt
  - pytorch
  - pytorch-gpu
  - jax
  - jaxlib
  - autograd >= 1.6.2
  - magma
  - pyvista >= 0.43.1
  - trame
  - nest-asyncio
  - ipywidgets
  - pip:
    - git+https://gitlab.com/nannos/nannos.git
