name: nannos
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - numpy
  - scipy
  - matplotlib-base
  - shapely
  - joblib
  - colorlog
  - psutil
  - ipython
  - jax
  - jaxlib
  - nlopt
  - pip:
    - autograd-latest
    - git+https://gitlab.com/nannos/nannos.git
